version: '3'

services:
      server:
        build:
          context: ./serverFolder
          dockerfile: Dockerfile.server
        networks:
          - mydockerNetwork
        volumes:
          - servervol:/serverdata

      client:
        build:
          context: ./clientFolder
          dockerfile: Dockerfile.client
        networks:
          - mydockerNetwork
        volumes:
          - clientvol:/clientdata
        depends_on:
          - server

networks:
  mydockerNetwork:
    driver: bridge
    name: mydockerNetwork

volumes:
  servervol:
  clientvol:
